// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZDjDkCFHrV2Whhd0aMWL-ibubEtAwaM',
    appId: '1:869048124095:web:7a7d1afcfaf27eb84c3c0a',
    messagingSenderId: '869048124095',
    projectId: 'w3dev-assignment',
    authDomain: 'w3dev-assignment.firebaseapp.com',
    storageBucket: 'w3dev-assignment.firebasestorage.app',
    measurementId: 'G-GLKGZMJ892',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-_F1yVWGJg2-oBy3phQDsMwQNt7n-o0',
    appId: '1:869048124095:android:94bd29d3d77957054c3c0a',
    messagingSenderId: '869048124095',
    projectId: 'w3dev-assignment',
    storageBucket: 'w3dev-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPSHJA1srLIShBuqpycYzNIPVjaHPzQQQ',
    appId: '1:869048124095:ios:5dff81867b69a60d4c3c0a',
    messagingSenderId: '869048124095',
    projectId: 'w3dev-assignment',
    storageBucket: 'w3dev-assignment.firebasestorage.app',
    iosBundleId: 'com.example.myAssignmentt',
  );
}
